name: Build

on:
  push:
    branches: master
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install dependencies
        run: |
          python -m pip install -U cookiecutter

      - name: Install the extension
        run: |
          cookiecutter . --config-file tests/testconfig.yaml --no-input
          pushd jupyter-widget-testwidgets
          python -m pip install --upgrade -v -e ".[test, examples, docs]"

      - name: Test the extension
        run: |
          pushd jupyter-widget-testwidgets
          yarn
          yarn run lint:check

          pytest
          yarn run test
          popd

      - name: Check docs can be build + links
        run: |
          sudo apt install -y pandoc
          pushd jupyter-widget-testwidgets/docs
          make html
          python -m pytest --check-links
          popd

      - name: Validate extension usage
        run: |
          # Validate nbextension
          jupyter nbextension list 2>&1 | grep -ie "jupyter-widget-testwidgets.*OK"

          # Validate labextension
          pip install -U jupyterlab~=3.0 jupyter_packaging~=0.7
          # Make sure our lab extension was installed.
          jupyter labextension list 2>&1 | grep -ie "jupyter-widget-testwidgets.*OK"
          # Make sure our lab extension can be develop installed.
          jupyter labextension develop . --overwrite

          popd
